eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    edu.microservices: DEBUG      
    
    
# this is to point to the auth server
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8901/user    
      
spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
      probability: 1.0