eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
      
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    edu.microservices: DEBUG      